### ISSUE TITLE
PHP warning due to direct inclusion of version.php

### ISSUE THREAD

**Issue by mudrd8mz** [martignoni/moodle-tool_moodlebox#10]
The index.php directly includes the version.php to be able to later display the release and version information. It throws the following PHP warning:
```
Warning: Creating default object from empty value in admin/tool/moodlebox/version.php on line 27
```
To avoid it, please initialize the empty {{$plugin}} object before including the version.php.

**Comment by martignoni** [comment]
Thanks. Already done, will push next version to plugin database ASAP.
