### ISSUE TITLE
Weird way of how checktime.js is included

### ISSUE THREAD

**Issue by mudrd8mz** [martignoni/moodle-tool_moodlebox#11]
I don't understand how the checktime() function is supposed to work and why is it loaded this way. Is not the server time passed as the first argument (the one called Y in the JS code)?

I would suggest to turn this into proper AMD module as you use other core modules anyway - please refer to https://docs.moodle.org/dev/Javascript_Modules

**Comment by martignoni** [comment]
OK. This one will be though (need to learn AMD :))

**Comment by martignoni** [comment]
Code is using now proper AMD mecanism. Closing.
