### ISSUE TITLE
Incomplete description at moodle.org/plugins

### ISSUE THREAD

**Issue by mudrd8mz** [martignoni/moodle-tool_moodlebox#13]
The description reads

> After the installation in Moodle, some steps are required to complete on the Raspberry Pi (see below).

There is not below and not steps are described there. I assume you wanted to document the cron job watching for the trigger files?

Additionally, the plugin implicitly expects that some kind of Linux is installed on the Raspberry Pi (which even if is the case in 99%, may or may not be always true). That and all other requirements should be properly documented.

**Comment by martignoni** [comment]
Oh, I dumbly thought that the README file was displayed "below". Is it OK to send users to read the README file (where the whole installation process is thoroughly described)?

**Comment by mudrd8mz** [comment]
Yes. Additionally you can use the URL https://github.com/martignoni/moodle-tool_moodlebox/blob/master/README.md as the value of the Documentation link to make it even easier.

**Comment by martignoni** [comment]
Done, thanks.
